name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - run: echo "export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
      - uses: actions/checkout@v2
      - uses: luchev/autograding@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
